services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - ./backend/.env
    ports:
      - "4000:3000"
    depends_on:
      - postgres

  postgres:
    image: "postgres:12"
    expose:
      - "5432"
    env_file: ./backend/.env
    # volumes:
    #   - postgres_data:/var/lib/postgresql/data/pgdata

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8081:80"
# volumes:
#   postgres_data:
